package views;

import controller.service.AccountingEntryService;
import controller.service.BuyInvoiceService;
import controller.service.PersonService;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import views.tableModel.BuyInvoiceTableModel;
import views.tableModel.PersonComboBoxModel;

public class BuyInvoiceView extends javax.swing.JDialog {

    private final BuyInvoiceService buyInvoiceService;
    private final PersonService personService;
    private final BuyInvoiceTableModel buyInvoiceTableModel;
    private final AccountingEntryService accountingEntryService; 
    private JTextField searchNameText;

    public BuyInvoiceView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.buyInvoiceService = new BuyInvoiceService();
        this.personService = new PersonService();
        this.buyInvoiceTableModel = new BuyInvoiceTableModel();
        this.accountingEntryService = new AccountingEntryService();
        initComponents();
        
        //Cargamos todos los proveedores en el combobox
        this.chargeSupplierCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        supplierSearchCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        supplierNames = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        supplierRuc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        supplierPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        supplierAddress = new javax.swing.JTextField();
        newEmployeeButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        buyInvoiceNumberTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buyInvoiceReferenceTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        buyInvoiceDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        buyInvoiceDescriptionTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        buyInvoiceTotalTxt = new javax.swing.JTextField();
        buyInvoiceSaveButton = new javax.swing.JButton();
        buyInvoiceCloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        jLabel1.setText("Buscar:");

        supplierSearchCombo.setEditable(true);
        supplierSearchCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                supplierSearchComboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel2.setText("Nombres:");

        supplierNames.setEditable(false);

        jLabel3.setText("RUC:");

        supplierRuc.setEditable(false);

        jLabel4.setText("Teléfono:");

        supplierPhone.setEditable(false);

        jLabel5.setText("Dirección:");

        supplierAddress.setEditable(false);

        newEmployeeButton.setText("NUEVO");
        newEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(supplierSearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(supplierAddress)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(supplierRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(supplierNames))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newEmployeeButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierSearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(supplierNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newEmployeeButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(supplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(supplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Factura de compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        jLabel6.setText("Número:");

        jLabel7.setText("Referencia:");

        jLabel8.setText("Fecha:");

        jLabel9.setText("Descripción:");

        jLabel10.setText("Total:");

        buyInvoiceSaveButton.setText("GUARDAR");
        buyInvoiceSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyInvoiceSaveButtonActionPerformed(evt);
            }
        });

        buyInvoiceCloseButton.setText("CERRAR");
        buyInvoiceCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyInvoiceCloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(buyInvoiceNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(2, 2, 2)
                                .addComponent(buyInvoiceReferenceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buyInvoiceDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(buyInvoiceTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180)
                                .addComponent(buyInvoiceSaveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buyInvoiceCloseButton)))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(buyInvoiceDescriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(buyInvoiceReferenceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addComponent(buyInvoiceDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buyInvoiceNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(buyInvoiceDescriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(buyInvoiceTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buyInvoiceSaveButton)
                            .addComponent(buyInvoiceCloseButton))))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buyInvoiceCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyInvoiceCloseButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buyInvoiceCloseButtonActionPerformed

    private void chargeSupplierCombo() {

        searchNameText = (JTextField) supplierSearchCombo.getComponent(2);
        searchNameText.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent evt) {
                if (evt.getKeyCode() == 27) {
                    supplierSearchCombo.setPopupVisible(false);
                    return;
                }
                if (evt.getKeyCode() == 10) {
                    if (supplierSearchCombo.getSelectedIndex() != - 1) {
                        PersonComboBoxModel pcm = (PersonComboBoxModel) supplierSearchCombo.getModel();
                        personService.setInstance(pcm.getSelectedItem());
                        chargeSupplierView();
                    }
                    supplierSearchCombo.setPopupVisible(false);
                    return;
                }

                if (evt.getKeyCode() == 40 || evt.getKeyCode() == 39 || evt.getKeyCode() == 38 || evt.getKeyCode() == 37
                        || evt.getKeyCode() == 36 || evt.getKeyCode() == 16 || evt.getKeyCode() == 35) {
                    return;
                }

                int position = searchNameText.getCaretPosition();
                String s = searchNameText.getText();
                supplierSearchCombo.setModel(new PersonComboBoxModel(personService.getSuppliersByCriteriaType(searchNameText.getText())));
                searchNameText.setText(s);

                searchNameText.setCaretPosition(position);
                supplierSearchCombo.setPopupVisible(true);
            }
        });
    }
    
    //Método para cargar un nuevo objeto tipo factura de compra
    private void chargeBuyInvoiceData() {
        this.buyInvoiceService.getBuyInvoice().setBuyInvoiceNumber(buyInvoiceNumberTxt.getText());
        this.buyInvoiceService.getBuyInvoice().setBuyInvoiceReference(buyInvoiceReferenceTxt.getText());
        this.buyInvoiceService.getBuyInvoice().setBuyInvoiceDate(buyInvoiceDateChooser.getDate());
        this.buyInvoiceService.getBuyInvoice().setBuyInvoiceDescription(buyInvoiceDescriptionTxt.getText());
        this.buyInvoiceService.getBuyInvoice().setBuyInvoiceTotal(Double.parseDouble(buyInvoiceTotalTxt.getText()));
        //Fijamos el proveedor a la factura
        this.buyInvoiceService.getBuyInvoice().setSupplier(this.personService.getPerson());
    }
    
    private void chargeSupplierView(){
        this.supplierNames.setText(this.personService.getPerson().toString());
        this.supplierRuc.setText(this.personService.getPerson().getPrIdentification());
        this.supplierAddress.setText(this.personService.getPerson().getPrAddress());
        this.supplierPhone.setText(this.personService.getPerson().getPrPhone());        
    }

    private void buyInvoiceSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyInvoiceSaveButtonActionPerformed
        // TODO add your handling code here:
        this.chargeBuyInvoiceData();
        if (this.buyInvoiceService.getBuyInvoice().getBuyInvoiceId() == null) {
            if (this.buyInvoiceService.saveBuyInvoice()) {
                JOptionPane.showMessageDialog(this, "LA FACTURA DE COMPRA SE HA GUARDADO CORRECTAMENTE");
                //this.buyInvoiceService.addBuyInvoiceItemList(this.buyInvoiceService.getBuyInvoice());
                //this.chargeBuyInvoiceTable();
                //Creamos una nueva entrada al asiento contable 
                this.chargeAccountingEntryData();
                if(this.accountingEntryService.saveAccountingEntry()){
                    System.out.println("El asiento contable ha sido guardado correctamente");
                    dispose();
                }
            }
        }
    }//GEN-LAST:event_buyInvoiceSaveButtonActionPerformed

    private void supplierSearchComboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_supplierSearchComboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (this.supplierSearchCombo.getItemCount() != 0) {
            PersonComboBoxModel pcbm = (PersonComboBoxModel) supplierSearchCombo.getModel();
            this.personService.setInstance(pcbm.getSelectedItem());
            if (this.personService.getPerson() != null) {
                this.chargeSupplierView();
            }
        }
    }//GEN-LAST:event_supplierSearchComboPopupMenuWillBecomeInvisible

    private void chargeAccountingEntryData(){
        this.accountingEntryService.getAccountingEntry().setAeType(1);
        this.accountingEntryService.getAccountingEntry().setAeCreatedDate(new Date());
        this.accountingEntryService.getAccountingEntry().setAeDescription("Factura de compra de: " + supplierNames.getText());
        this.accountingEntryService.getAccountingEntry().setAeValue(Double.parseDouble(buyInvoiceTotalTxt.getText()));
    }
    
    private void chargeBuyInvoiceTable(){
        this.buyInvoiceTableModel.setLista(this.buyInvoiceService.getBuyInvoceList());
        //this.buyInvoiceTable.setModel(buyInvoiceTableModel);
        //this.buyInvoiceTable.updateUI();
    }
    
    private void newEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeButtonActionPerformed
        // TODO add your handling code here:
        new PersonView(null, true, 1).setVisible(true);
    }//GEN-LAST:event_newEmployeeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyInvoiceCloseButton;
    private com.toedter.calendar.JDateChooser buyInvoiceDateChooser;
    private javax.swing.JTextField buyInvoiceDescriptionTxt;
    private javax.swing.JTextField buyInvoiceNumberTxt;
    private javax.swing.JTextField buyInvoiceReferenceTxt;
    private javax.swing.JButton buyInvoiceSaveButton;
    private javax.swing.JTextField buyInvoiceTotalTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton newEmployeeButton;
    private javax.swing.JTextField supplierAddress;
    private javax.swing.JTextField supplierNames;
    private javax.swing.JTextField supplierPhone;
    private javax.swing.JTextField supplierRuc;
    private javax.swing.JComboBox<String> supplierSearchCombo;
    // End of variables declaration//GEN-END:variables
}