package views;

import model.Person;
import java.awt.Color;
import controller.resources.NumberToLetter;
import controller.resources.Operaciones;
import controller.service.InvoiceService;
import controller.service.WorkOrderService;

public class CambioV extends javax.swing.JDialog {

    private double totalVenta;
    private Person cliente;
    private final InvoiceService invs;
    private Operaciones uccfactura;
    private final WorkOrderService workOrderService;
    private int changeState;

    public CambioV(java.awt.Frame parent, boolean modal, double val, InvoiceService invs) {
        super(parent, modal);
        totalVenta = val;
//        cliente = client;
//        factures = facture;
        this.invs = invs;
        uccfactura = new Operaciones();
        workOrderService = new WorkOrderService();
        initComponents();
        changeState = 1;
        totalSell.setText(uccfactura.parteDecimal(val, 2) + "");
        setLocationRelativeTo(this);
    }

    public CambioV(java.awt.Frame parent, boolean modal, double val, WorkOrderService workOrderService) {
        super(parent, modal);
        totalVenta = val;
//        cliente = client;
//        factures = facture;
        this.invs = new InvoiceService();
        this.workOrderService = workOrderService;
        uccfactura = new Operaciones();
        initComponents();
        changeState = 2;
        totalSell.setText(uccfactura.parteDecimal(val, 2) + "");
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVuelto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        acceptButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        totalSell = new javax.swing.JTextField();
        vueltCliente = new javax.swing.JTextField();
        numberToLetterLabel = new javax.swing.JLabel();
        clientCant = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CAMBIO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelVuelto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("CANTIDAD DADA POR EL CLIENTE:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Ej: $ 0,50");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel3.setText("$");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("CANTIDAD TOTAL DE LA VENTA:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("CAMBIO PARA EL CLIENTE:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel6.setText("$");

        acceptButton.setFont(new java.awt.Font("Tahoma", 1, 18));
        acceptButton.setText("ACEPTAR");
        acceptButton.setEnabled(false);
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel7.setText("$");

        totalSell.setBackground(new java.awt.Color(102, 51, 255));
        totalSell.setEditable(false);
        totalSell.setFont(new java.awt.Font("Tahoma", 1, 36));
        totalSell.setForeground(new java.awt.Color(255, 255, 102));
        totalSell.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalSell.setText("0.00");

        vueltCliente.setBackground(new java.awt.Color(204, 255, 0));
        vueltCliente.setEditable(false);
        vueltCliente.setFont(new java.awt.Font("Tahoma", 1, 36));
        vueltCliente.setForeground(new java.awt.Color(204, 0, 204));
        vueltCliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vueltCliente.setText("0.00");

        numberToLetterLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        numberToLetterLabel.setText("...");

        clientCant.setFont(new java.awt.Font("Tahoma", 1, 36));
        clientCant.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        clientCant.setText("0.00");
        clientCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientCantActionPerformed(evt);
            }
        });
        clientCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clientCantKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clientCantKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelVueltoLayout = new javax.swing.GroupLayout(panelVuelto);
        panelVuelto.setLayout(panelVueltoLayout);
        panelVueltoLayout.setHorizontalGroup(
            panelVueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVueltoLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelVueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(totalSell, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(vueltCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(numberToLetterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVueltoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelVueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clientCant)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(59, 59, 59))
            .addGroup(panelVueltoLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        panelVueltoLayout.setVerticalGroup(
            panelVueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVueltoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelVueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVueltoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2))
                    .addGroup(panelVueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clientCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vueltCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberToLetterLabel)
                .addGap(18, 18, 18)
                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVuelto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void action() {

        if (acceptButton.isEnabled()) {

            if (changeState == 1) {
                this.invs.getInvoice().setInChange(Double.parseDouble(vueltCliente.getText()));
                this.invs.getInvoice().setInCash(Double.valueOf(clientCant.getText()));
                dispose();
            } else {
                this.workOrderService.getWorkOrder().setWorkOrderChange(Double.parseDouble(vueltCliente.getText()));
                this.workOrderService.getWorkOrder().setWorkOrderCash(Double.valueOf(clientCant.getText()));
                dispose();
            }

        }
    }
    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        action();
    }//GEN-LAST:event_acceptButtonActionPerformed

    public void calcular() {
        try {
            numberToLetterLabel.setForeground(Color.black);
            double cantC = Double.parseDouble(clientCant.getText());
            double valVuelto = cantC - totalVenta;
            vueltCliente.setText(uccfactura.parteDecimal(uccfactura.formatToDecimales(valVuelto, 2), 2) + "");
            NumberToLetter nt = new NumberToLetter();
            numberToLetterLabel.setText(nt.convertirALetras(Double.parseDouble(vueltCliente.getText())));
            if (Double.parseDouble(vueltCliente.getText()) < 0) {
                acceptButton.setEnabled(false);
            } else {
                acceptButton.setEnabled(true);
            }

        } catch (Exception ex) {
            numberToLetterLabel.setForeground(Color.red);
            numberToLetterLabel.setText("Cantidad Incorrecta");
            acceptButton.setEnabled(false);
        }
    }

    private void clientCantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientCantKeyReleased
        calcular();
    }//GEN-LAST:event_clientCantKeyReleased

    private void clientCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientCantKeyTyped
        Operaciones.soloNumerosDecimales(evt, clientCant.getText());
    }//GEN-LAST:event_clientCantKeyTyped

    private void clientCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientCantActionPerformed
        action();
    }//GEN-LAST:event_clientCantActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        factures.setCash(0);
//        factures.setChange(0);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JTextField clientCant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel numberToLetterLabel;
    private javax.swing.JPanel panelVuelto;
    private javax.swing.JTextField totalSell;
    private javax.swing.JTextField vueltCliente;
    // End of variables declaration//GEN-END:variables

}
