package views;

import controller.resources.Message;
import controller.service.AccountingEntryService;
import controller.service.InvoiceService;
import java.util.Date;
import javax.swing.JOptionPane;
import views.tableModel.InvoiceTableModel;

public class CancelInvoice extends javax.swing.JDialog {

    private final InvoiceService invService;
    private final AccountingEntryService aeService;
    private final InvoiceTableModel itm;

    public CancelInvoice(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.invService = new InvoiceService();
        this.itm = new InvoiceTableModel();
        this.aeService = new AccountingEntryService();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        startDateJDC = new com.toedter.calendar.JDateChooser();
        finalDateJDC = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        searchFactureBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchInvoiceTable = new javax.swing.JTable();
        anularFactura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSCAR FACTURA"));

        jLabel1.setText("Desde:");

        startDateJDC.setDate(new Date());

        finalDateJDC.setDate(new Date());

        jLabel2.setText("Hasta:");

        searchFactureBt.setText("BUSCAR");
        searchFactureBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFactureBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startDateJDC, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalDateJDC, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchFactureBt)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchFactureBt)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(finalDateJDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(startDateJDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchInvoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        searchInvoiceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchInvoiceTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(searchInvoiceTable);

        anularFactura.setText("Anular Factura");
        anularFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anularFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(anularFactura))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anularFactura)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchFactureBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFactureBtActionPerformed
        // TODO add your handling code here:
        this.itm.setLista(this.invService.listInvoicePerDateRange(startDateJDC, finalDateJDC));
        this.searchInvoiceTable.setModel(itm);
        this.searchInvoiceTable.updateUI();

    }//GEN-LAST:event_searchFactureBtActionPerformed

    private void searchInvoiceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchInvoiceTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            this.invService.setInstance(itm.getLista().get(searchInvoiceTable.getSelectedRow()));
        }else{
            JOptionPane.showMessageDialog(this, "NO HA SELECCIONADO NINGUNA FACTURA");
        }
    }//GEN-LAST:event_searchInvoiceTableMouseClicked

    private void anularFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anularFacturaActionPerformed
        // TODO add your handling code here:
        if(startDateJDC.getDate() != null && finalDateJDC.getDate() != null){
            
        }else{
          JOptionPane.showMessageDialog(this, "CAMPOS DE FECHA VACIOS");  
        }
        if (this.invService.getInvoice().getInState().equals("ANULADA")) {
            JOptionPane.showMessageDialog(this, "LA FACTURA YA ESTA ANULADA");
        } else {
            if(Message.confirmOption("Desea anular la factura seleccionada?")){
                this.invService.getInvoice().setInState("ANULADA");
                if(this.invService.updateInvoice()){
                    JOptionPane.showMessageDialog(this, "SE HA ANULADO LA FACTURA");
                    this.saveAccountingEntry();
                    this.searchInvoiceTable.updateUI();
                } 
            }    
        }
    }//GEN-LAST:event_anularFacturaActionPerformed

    private void saveAccountingEntry() {
        this.aeService.getAccountingEntry().setAeCreatedDate(new Date());
        this.aeService.getAccountingEntry().setAeDescription("Anula Factura de venta Nro: " + this.invService.getInvoice().getInNumber());
        this.aeService.getAccountingEntry().setAeType(1);
        this.aeService.getAccountingEntry().setAeValue(this.invService.getInvoice().getInTotal());

        if (this.aeService.getAccountingEntry().getAccountingEntryId() == null) {
            if (this.aeService.saveAccountingEntry()) {
                System.out.println("Asiento guardado correctamente");
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CancelInvoice dialog = new CancelInvoice(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anularFactura;
    private com.toedter.calendar.JDateChooser finalDateJDC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchFactureBt;
    private javax.swing.JTable searchInvoiceTable;
    private com.toedter.calendar.JDateChooser startDateJDC;
    // End of variables declaration//GEN-END:variables
}
