package views;

import controller.resources.GeneralParameter;
import controller.resources.Operaciones;
import controller.resources.Report;
import javax.swing.JOptionPane;
import controller.service.AccountingEntryService;
import controller.service.CashClosingService;
import java.util.Date;

public class ClosingCashView extends javax.swing.JDialog {

    private final CashClosingService ccs;
    private final AccountingEntryService aes;

    private double billTotal = 0;
    private double coinTotal = 0;
    private double sysInflowTotal = 0;
    private double cashierInflowTotal = 0;
    private double sysCashTotal = 0;
    private double outflowTotal = 0;
    private double reicivableTotal = 0;
    private double cashTotal = 0;
    private double oDollars = 0;
    private double fDollars = 0;
    private double tDollars = 0;
    private double twDollars = 0;
    private double ftDollars = 0;
    private double ohDollars = 0;
    private double oCent = 0;
    private double fCents = 0;
    private double tCents = 0;
    private double tfCents = 0;
    private double ftCents = 0;
    private double ohCents = 0;
    private double sysCashInit = 0;
    private double sysTotalCheks = 0;
    private double sysTotalCreditCard = 0;
    private double sysTotalDebitCard = 0;
    private double cashierCash = 0;
    private double cashierTotalCheks = 0;
    private double cashierTotalCreditCard = 0;
    private double cashierTotalDebitCard = 0;
    
    private final Double auxTot;

    public ClosingCashView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.ccs = new CashClosingService();
        this.aes = new AccountingEntryService();
        this.auxTot = Math.pow(10, GeneralParameter.ACCURACY_VALUE);
        initComponents();
        this.outflowTotalCalculate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aCCPetitionNoteSp = new javax.swing.JScrollPane();
        aCCPetitionNoteTable = new javax.swing.JTable();
        aCCPetitionNotePopup = new javax.swing.JPopupMenu();
        aCCDeliveryNoteSp = new javax.swing.JScrollPane();
        aCCDeliveryNoteTable = new javax.swing.JTable();
        aCCDeliveryNotePopup = new javax.swing.JPopupMenu();
        aCCFactureSp = new javax.swing.JScrollPane();
        aCCFactureTable = new javax.swing.JTable();
        aCCFacturePopup = new javax.swing.JPopupMenu();
        aCCEgressSp = new javax.swing.JScrollPane();
        aCCEgressTable = new javax.swing.JTable();
        aCCEgressPopup = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cCashDateFrom = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        cCashDateTo = new com.toedter.calendar.JDateChooser();
        aCCFacturePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sysCashInittxt = new javax.swing.JTextField();
        sysCashtxt = new javax.swing.JTextField();
        sysChekstxt = new javax.swing.JTextField();
        sysCreditCardtxt = new javax.swing.JTextField();
        sysDebitCardtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cashierCashtxt = new javax.swing.JTextField();
        cashierCheckstxt = new javax.swing.JTextField();
        cashierCreditCardtxt = new javax.swing.JTextField();
        cashierDebitCardtxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        sysInflowTotalTxt = new javax.swing.JTextField();
        cashierInflowTotalTxt = new javax.swing.JTextField();
        cCashBt = new javax.swing.JButton();
        cCashCloseBt = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        reicivableTotalTxt = new javax.swing.JTextField();
        cashTotalTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        outflowTotalTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        oneDollarSp = new javax.swing.JSpinner();
        fiveDollarsSp = new javax.swing.JSpinner();
        tenDollarsSp = new javax.swing.JSpinner();
        twentyDollarsSp = new javax.swing.JSpinner();
        fiftyDollarsSp = new javax.swing.JSpinner();
        oneHundredDollarsSp = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        oneCentSp = new javax.swing.JSpinner();
        fiveCentsSp = new javax.swing.JSpinner();
        tenCentsSp = new javax.swing.JSpinner();
        twentyFiveCentsSp = new javax.swing.JSpinner();
        fiftyCentsSp = new javax.swing.JSpinner();
        oneDolarCoinSp = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        billTotalTxt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        coinTotalTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        closingCashObservations = new javax.swing.JTextArea();

        aCCPetitionNotePopup.add(aCCPetitionNoteSp);

        aCCPetitionNoteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        aCCPetitionNoteSp.setViewportView(aCCPetitionNoteTable);

        aCCDeliveryNotePopup.add(aCCDeliveryNoteSp);

        aCCDeliveryNoteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        aCCDeliveryNoteSp.setViewportView(aCCDeliveryNoteTable);

        aCCFacturePopup.add(aCCFactureSp);

        aCCFactureTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        aCCFactureSp.setViewportView(aCCFactureTable);

        aCCEgressPopup.add(aCCEgressSp);

        aCCEgressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        aCCEgressSp.setViewportView(aCCEgressTable);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CIERRE DE CAJA DIARIO");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setText("Desde:");

        cCashDateFrom.setDate(new Date());
        cCashDateFrom.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setText("Hasta:");

        cCashDateTo.setDate(new Date());
        cCashDateTo.setEnabled(false);

        aCCFacturePanel.setBackground(new java.awt.Color(255, 255, 255));
        aCCFacturePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOTALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 13), new java.awt.Color(0, 153, 255))); // NOI18N
        aCCFacturePanel.setPreferredSize(new java.awt.Dimension(248, 163));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("Efectivo:");

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel15.setText("Inicio de Caja:");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Cheque:");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("Tarjeta de Crédito:");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setText("Tarjeta Débito:");

        sysCashInittxt.setEditable(false);
        sysCashInittxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        sysCashInittxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sysCashInittxt.setText("0.00");

        sysCashtxt.setEditable(false);
        sysCashtxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        sysCashtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sysCashtxt.setText("0.00");

        sysChekstxt.setEditable(false);
        sysChekstxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        sysChekstxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sysChekstxt.setText("0.00");

        sysCreditCardtxt.setEditable(false);
        sysCreditCardtxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        sysCreditCardtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sysCreditCardtxt.setText("0.00");
        sysCreditCardtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sysCreditCardtxtActionPerformed(evt);
            }
        });

        sysDebitCardtxt.setEditable(false);
        sysDebitCardtxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        sysDebitCardtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sysDebitCardtxt.setText("0.00");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setText("SISTEMA");

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setText("CAJERO");

        cashierCashtxt.setEditable(false);
        cashierCashtxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cashierCashtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cashierCashtxt.setText("0.00");
        cashierCashtxt.setToolTipText("");

        cashierCheckstxt.setEditable(false);
        cashierCheckstxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cashierCheckstxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cashierCheckstxt.setText("0.00");

        cashierCreditCardtxt.setEditable(false);
        cashierCreditCardtxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cashierCreditCardtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cashierCreditCardtxt.setText("0.00");

        cashierDebitCardtxt.setEditable(false);
        cashierDebitCardtxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cashierDebitCardtxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cashierDebitCardtxt.setText("0.00");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setText("Total Ingresos:");

        sysInflowTotalTxt.setEditable(false);
        sysInflowTotalTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        sysInflowTotalTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sysInflowTotalTxt.setText("0.00");

        cashierInflowTotalTxt.setEditable(false);
        cashierInflowTotalTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cashierInflowTotalTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cashierInflowTotalTxt.setText("0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sysInflowTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cashierInflowTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sysInflowTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashierInflowTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout aCCFacturePanelLayout = new javax.swing.GroupLayout(aCCFacturePanel);
        aCCFacturePanel.setLayout(aCCFacturePanelLayout);
        aCCFacturePanelLayout.setHorizontalGroup(
            aCCFacturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aCCFacturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aCCFacturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aCCFacturePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9)
                        .addGap(53, 53, 53))
                    .addGroup(aCCFacturePanelLayout.createSequentialGroup()
                        .addGroup(aCCFacturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(aCCFacturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sysCashInittxt, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(sysCashtxt)
                            .addComponent(sysChekstxt)
                            .addComponent(sysCreditCardtxt)
                            .addComponent(sysDebitCardtxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(aCCFacturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cashierCreditCardtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(cashierCheckstxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashierCashtxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashierDebitCardtxt))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(aCCFacturePanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        aCCFacturePanelLayout.setVerticalGroup(
            aCCFacturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aCCFacturePanelLayout.createSequentialGroup()
                .addGroup(aCCFacturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aCCFacturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(sysCashInittxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aCCFacturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sysCashtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashierCashtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aCCFacturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sysChekstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashierCheckstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aCCFacturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sysCreditCardtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashierCreditCardtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aCCFacturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sysDebitCardtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashierDebitCardtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        cCashBt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cCashBt.setText("CIERRE DE CAJA");
        cCashBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCashBtActionPerformed(evt);
            }
        });

        cCashCloseBt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cCashCloseBt.setText("CERRAR");
        cCashCloseBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCashCloseBtActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel19.setText("TOTAL POR COBRAR:");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("TOTAL EN CAJA:");

        reicivableTotalTxt.setEditable(false);
        reicivableTotalTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        reicivableTotalTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        reicivableTotalTxt.setText("0.00");

        cashTotalTxt.setEditable(false);
        cashTotalTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cashTotalTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cashTotalTxt.setText("0.00");

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setText("TOTAL EGRESOS:");

        outflowTotalTxt.setEditable(false);
        outflowTotalTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        outflowTotalTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        outflowTotalTxt.setText("0.00");
        outflowTotalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outflowTotalTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reicivableTotalTxt)
                            .addComponent(outflowTotalTxt)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cashTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(455, 455, 455))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(outflowTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(reicivableTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(43, 43, 43))
        );

        jTabbedPane1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setText("BILLETE DE 1:");

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel13.setText("BILLETE DE 5:");

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel14.setText("BILLETE DE 10:");

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel16.setText("BILLETE DE 20:");

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel17.setText("BILLETE DE 50:");

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel18.setText("BILLETE DE 100:");

        oneDollarSp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        oneDollarSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                oneDollarSpStateChanged(evt);
            }
        });
        oneDollarSp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                oneDollarSpPropertyChange(evt);
            }
        });

        fiveDollarsSp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fiveDollarsSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fiveDollarsSpStateChanged(evt);
            }
        });
        fiveDollarsSp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fiveDollarsSpPropertyChange(evt);
            }
        });

        tenDollarsSp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tenDollarsSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tenDollarsSpStateChanged(evt);
            }
        });

        twentyDollarsSp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        twentyDollarsSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                twentyDollarsSpStateChanged(evt);
            }
        });

        fiftyDollarsSp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fiftyDollarsSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fiftyDollarsSpStateChanged(evt);
            }
        });

        oneHundredDollarsSp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        oneHundredDollarsSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                oneHundredDollarsSpStateChanged(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel22.setText("MONEDA DE 0.01:");

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel23.setText("MONEDA DE 0.05:");

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel24.setText("MONEDA DE 0.10:");

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel25.setText("MONEDA DE 0.25:");

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel26.setText("MONEDA DE 0.50:");

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel27.setText("MONEDA DE 1.00:");

        oneCentSp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        oneCentSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                oneCentSpStateChanged(evt);
            }
        });

        fiveCentsSp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fiveCentsSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fiveCentsSpStateChanged(evt);
            }
        });

        tenCentsSp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tenCentsSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tenCentsSpStateChanged(evt);
            }
        });

        twentyFiveCentsSp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        twentyFiveCentsSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                twentyFiveCentsSpStateChanged(evt);
            }
        });

        fiftyCentsSp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fiftyCentsSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fiftyCentsSpStateChanged(evt);
            }
        });

        oneDolarCoinSp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        oneDolarCoinSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                oneDolarCoinSpStateChanged(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 255));
        jLabel28.setText("Total Billetes:");

        billTotalTxt.setEditable(false);
        billTotalTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        billTotalTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        billTotalTxt.setText("0.00");

        jLabel29.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 153, 255));
        jLabel29.setText("Total Monedas:");

        coinTotalTxt.setEditable(false);
        coinTotalTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        coinTotalTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        coinTotalTxt.setText("0.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(fiftyDollarsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oneHundredDollarsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(twentyDollarsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tenDollarsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fiveDollarsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oneDollarSp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(oneCentSp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fiftyCentsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(twentyFiveCentsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tenCentsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fiveCentsSp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel29)
                                            .addComponent(jLabel27))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(oneDolarCoinSp, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(billTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addComponent(coinTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(oneDollarSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel13)
                            .addComponent(fiveDollarsSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(fiveCentsSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel14)
                            .addComponent(tenDollarsSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(tenCentsSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel16)
                            .addComponent(twentyDollarsSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(twentyFiveCentsSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel17)
                            .addComponent(fiftyDollarsSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(fiftyCentsSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel18)
                            .addComponent(oneHundredDollarsSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(oneDolarCoinSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(billTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel22)
                            .addComponent(oneCentSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(173, 173, 173)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coinTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Efectivo", jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OBSERVACIONES:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        closingCashObservations.setColumns(20);
        closingCashObservations.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        closingCashObservations.setRows(5);
        jScrollPane1.setViewportView(closingCashObservations);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aCCFacturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cCashBt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cCashCloseBt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(cCashDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(cCashDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(cCashDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cCashDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(aCCFacturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cCashBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cCashCloseBt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void outflowTotalCalculate() {
        //fijamos a la lista de asientos contables el resultado de los registros de una fecha específica
        this.aes.setAccountingEntryList(this.aes.listByCurrentDate(new Date()));
        //Si no tiene datos de ingresos y egresos muestra un mensaje
        //If don´t have data of inflows and outflows show a message
        if (this.aes.getAccountingEntryList().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existen valores para el cierre de caja");
        } else {
            //Método para calcular el total de los ingresos y egresos
            for (int i = 0; i < this.aes.getAccountingEntryList().size(); i++) {
                if (this.aes.getAccountingEntryList().get(i).getAeType().equals(0)) {
                    sysCashTotal += this.aes.getAccountingEntryList().get(i).getAeValue();
                } else {
                    outflowTotal += this.aes.getAccountingEntryList().get(i).getAeValue();
                }
            }
            sysCashInittxt.setText(String.valueOf(Operaciones.parteDecimal(Math.rint(this.aes.getAccountingEntryList().get(0).getAeValue()*auxTot)/auxTot,GeneralParameter.ACCURACY_VALUE)));
            sysCashTotal -= this.aes.getAccountingEntryList().get(0).getAeValue();
            sysCashtxt.setText(String.valueOf(Operaciones.parteDecimal(Math.rint(sysCashTotal*auxTot)/auxTot, GeneralParameter.ACCURACY_VALUE)));
            outflowTotalTxt.setText(String.valueOf(Operaciones.parteDecimal(Math.rint(outflowTotal*auxTot)/auxTot, GeneralParameter.ACCURACY_VALUE)));
            //Calculamos los totales, ingresos, egresos y cuentas por cobrar y fijamos la los valores en la vista.
            this.totalCalculate();
        }
    }

    private void cCashCloseBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCashCloseBtActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cCashCloseBtActionPerformed

    private void cCashBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCashBtActionPerformed
        // TODO add your handling code here:
        if (this.aes.getAccountingEntryList().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existen datos para el cierre de caja");
        } else {
            if (this.ccs.getCashClosing().getClosingCashId() == null) {
                this.chargeClosingCashData();
                if (this.ccs.saveCashClosing()) {
                    JOptionPane.showMessageDialog(this, "EL CIERRE DE CAJA SE HA REALIZADO CORRECTAMENTE");
                    Report rp = new Report();
                    rp.printClosingCash(this.ccs);
                    dispose();
                }
            }
        }
    }//GEN-LAST:event_cCashBtActionPerformed

    private void sysCreditCardtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sysCreditCardtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sysCreditCardtxtActionPerformed

    private void oneDollarSpPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_oneDollarSpPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_oneDollarSpPropertyChange

    private void fiveDollarsSpPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fiveDollarsSpPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_fiveDollarsSpPropertyChange

    private void oneDollarSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_oneDollarSpStateChanged
        // TODO add your handling code here:
        oDollars = Double.valueOf(String.valueOf(oneDollarSp.getValue())) * 1;
        this.totalCalculate();
    }//GEN-LAST:event_oneDollarSpStateChanged

    private void fiveDollarsSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fiveDollarsSpStateChanged
        // TODO add your handling code here:
        fDollars = Double.valueOf(String.valueOf(fiveDollarsSp.getValue())) * 5;
        this.totalCalculate();

    }//GEN-LAST:event_fiveDollarsSpStateChanged

    private void tenDollarsSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tenDollarsSpStateChanged
        // TODO add your handling code here:
        tDollars = Double.valueOf(String.valueOf(tenDollarsSp.getValue())) * 10;
        this.totalCalculate();
    }//GEN-LAST:event_tenDollarsSpStateChanged

    private void twentyDollarsSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_twentyDollarsSpStateChanged
        // TODO add your handling code here:
        twDollars = Double.valueOf(String.valueOf(twentyDollarsSp.getValue())) * 20;
        this.totalCalculate();
    }//GEN-LAST:event_twentyDollarsSpStateChanged

    private void fiftyDollarsSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fiftyDollarsSpStateChanged
        // TODO add your handling code here:
        ftDollars = Double.valueOf(String.valueOf(fiftyDollarsSp.getValue())) * 50;
        this.totalCalculate();
    }//GEN-LAST:event_fiftyDollarsSpStateChanged

    private void oneHundredDollarsSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_oneHundredDollarsSpStateChanged
        // TODO add your handling code here:
        ohDollars = Double.valueOf(String.valueOf(oneHundredDollarsSp.getValue())) * 100;
        this.totalCalculate();
    }//GEN-LAST:event_oneHundredDollarsSpStateChanged

    private void oneCentSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_oneCentSpStateChanged
        // TODO add your handling code here:
        oCent = Double.valueOf(String.valueOf(oneCentSp.getValue())) * 0.01;
        this.totalCalculate();
    }//GEN-LAST:event_oneCentSpStateChanged

    private void fiveCentsSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fiveCentsSpStateChanged
        // TODO add your handling code here:
        fCents = Double.valueOf(String.valueOf(fiveCentsSp.getValue())) * 0.05;
        this.totalCalculate();
    }//GEN-LAST:event_fiveCentsSpStateChanged

    private void tenCentsSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tenCentsSpStateChanged
        // TODO add your handling code here:
        tCents = Double.valueOf(String.valueOf(tenCentsSp.getValue())) * 0.10;
        this.totalCalculate();
    }//GEN-LAST:event_tenCentsSpStateChanged

    private void twentyFiveCentsSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_twentyFiveCentsSpStateChanged
        // TODO add your handling code here:
        tfCents = Double.valueOf(String.valueOf(twentyFiveCentsSp.getValue())) * 0.25;
        this.totalCalculate();
    }//GEN-LAST:event_twentyFiveCentsSpStateChanged

    private void fiftyCentsSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fiftyCentsSpStateChanged
        // TODO add your handling code here:
        ftCents = Double.valueOf(String.valueOf(fiftyCentsSp.getValue())) * 0.50;
        this.totalCalculate();
    }//GEN-LAST:event_fiftyCentsSpStateChanged

    private void oneDolarCoinSpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_oneDolarCoinSpStateChanged
        // TODO add your handling code here:
        ohCents = Double.valueOf(String.valueOf(oneDolarCoinSp.getValue())) * 1;
        this.totalCalculate();
    }//GEN-LAST:event_oneDolarCoinSpStateChanged

    private void outflowTotalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outflowTotalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outflowTotalTxtActionPerformed

    private void spinnerControl() {
        oneDollarSp.setEnabled(Boolean.TRUE);
        fiveDollarsSp.setEnabled(Boolean.TRUE);
        tenDollarsSp.setEnabled(Boolean.TRUE);
        twentyDollarsSp.setEnabled(Boolean.TRUE);
        fiftyDollarsSp.setEnabled(Boolean.TRUE);
        oneHundredDollarsSp.setEnabled(Boolean.TRUE);

        oneCentSp.setEnabled(Boolean.TRUE);
        fiveCentsSp.setEnabled(Boolean.TRUE);
        tenCentsSp.setEnabled(Boolean.TRUE);
        twentyFiveCentsSp.setEnabled(Boolean.TRUE);
        fiftyCentsSp.setEnabled(Boolean.TRUE);
        oneDolarCoinSp.setEnabled(Boolean.TRUE);
    }

    private void spinnerDisableControl() {
        oneDollarSp.setEnabled(Boolean.FALSE);
        fiveDollarsSp.setEnabled(Boolean.FALSE);
        tenDollarsSp.setEnabled(Boolean.FALSE);
        twentyDollarsSp.setEnabled(Boolean.FALSE);
        fiftyDollarsSp.setEnabled(Boolean.FALSE);
        oneHundredDollarsSp.setEnabled(Boolean.FALSE);

        oneCentSp.setEnabled(Boolean.FALSE);
        fiveCentsSp.setEnabled(Boolean.FALSE);
        tenCentsSp.setEnabled(Boolean.FALSE);
        twentyFiveCentsSp.setEnabled(Boolean.FALSE);
        fiftyCentsSp.setEnabled(Boolean.FALSE);
        oneDolarCoinSp.setEnabled(Boolean.FALSE);
    }

    private void totalCalculate() {
        billTotal = oDollars + fDollars + tDollars + twDollars + ftDollars + ohDollars;
        billTotalTxt.setText(String.valueOf(Operaciones.parteDecimal(Math.rint(billTotal*auxTot)/auxTot, GeneralParameter.ACCURACY_VALUE)));
        
        coinTotal = oCent + fCents + tCents + tfCents + ftCents + ohCents;
        
        coinTotalTxt.setText(String.valueOf(Operaciones.parteDecimal(Math.rint(coinTotal*auxTot)/auxTot, GeneralParameter.ACCURACY_VALUE)));
        cashierCashtxt.setText(String.valueOf(Operaciones.parteDecimal(Math.rint((billTotal + coinTotal)*auxTot)/auxTot, GeneralParameter.ACCURACY_VALUE)));
        cashierCash = Double.valueOf(cashierCashtxt.getText());
        
        cashierInflowTotal = cashierCash + cashierTotalCheks + cashierTotalCreditCard + cashierTotalDebitCard;
        
        cashierInflowTotalTxt.setText(String.valueOf(Operaciones.parteDecimal(Math.rint(cashierInflowTotal*auxTot)/auxTot, GeneralParameter.ACCURACY_VALUE)));
        reicivableTotal = Double.valueOf(reicivableTotalTxt.getText());
        sysCashInit = Double.valueOf(sysCashInittxt.getText());
        
        sysInflowTotal = sysCashInit + sysCashTotal + sysTotalCheks + sysTotalCreditCard + sysTotalDebitCard;
        
        sysInflowTotalTxt.setText(String.valueOf(Operaciones.parteDecimal(Math.rint(sysInflowTotal*auxTot)/auxTot, GeneralParameter.ACCURACY_VALUE)));
        
        cashTotal = sysInflowTotal - outflowTotal;
        
        cashTotalTxt.setText(String.valueOf(Operaciones.parteDecimal(Math.rint(cashTotal*auxTot)/auxTot, GeneralParameter.ACCURACY_VALUE)));
    }

    private void chargeClosingCashData() {
        this.ccs.getCashClosing().setCcDateFrom(cCashDateFrom.getDate());
        this.ccs.getCashClosing().setCcDateTo(cCashDateTo.getDate());
        this.ccs.getCashClosing().setCcInitialCashValue(sysCashInit);
        this.ccs.getCashClosing().setCcTotalCash(sysCashTotal);
        this.ccs.getCashClosing().setCcTotalCheks(sysTotalCheks);
        this.ccs.getCashClosing().setCcTotalCreditCard(sysTotalCreditCard);
        this.ccs.getCashClosing().setCcTotalDebitCard(sysTotalDebitCard);
        this.ccs.getCashClosing().setCcTotalInflow(sysInflowTotal);
        this.ccs.getCashClosing().setCcTotalOutflow(outflowTotal);
        this.ccs.getCashClosing().setCcTotalReceivableAccounts(reicivableTotal);
        this.ccs.getCashClosing().setCcTotal(cashTotal);
        this.ccs.getCashClosing().setCcObservation(closingCashObservations.getText());
    }

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ClosingCashView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ClosingCashView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ClosingCashView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ClosingCashView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ClosingCashView dialog = new ClosingCashView(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu aCCDeliveryNotePopup;
    private javax.swing.JScrollPane aCCDeliveryNoteSp;
    private javax.swing.JTable aCCDeliveryNoteTable;
    private javax.swing.JPopupMenu aCCEgressPopup;
    private javax.swing.JScrollPane aCCEgressSp;
    private javax.swing.JTable aCCEgressTable;
    private javax.swing.JPanel aCCFacturePanel;
    private javax.swing.JPopupMenu aCCFacturePopup;
    private javax.swing.JScrollPane aCCFactureSp;
    private javax.swing.JTable aCCFactureTable;
    private javax.swing.JPopupMenu aCCPetitionNotePopup;
    private javax.swing.JScrollPane aCCPetitionNoteSp;
    private javax.swing.JTable aCCPetitionNoteTable;
    private javax.swing.JTextField billTotalTxt;
    private javax.swing.JButton cCashBt;
    private javax.swing.JButton cCashCloseBt;
    private com.toedter.calendar.JDateChooser cCashDateFrom;
    private com.toedter.calendar.JDateChooser cCashDateTo;
    private javax.swing.JTextField cashTotalTxt;
    private javax.swing.JTextField cashierCashtxt;
    private javax.swing.JTextField cashierCheckstxt;
    private javax.swing.JTextField cashierCreditCardtxt;
    private javax.swing.JTextField cashierDebitCardtxt;
    private javax.swing.JTextField cashierInflowTotalTxt;
    private javax.swing.JTextArea closingCashObservations;
    private javax.swing.JTextField coinTotalTxt;
    private javax.swing.JSpinner fiftyCentsSp;
    private javax.swing.JSpinner fiftyDollarsSp;
    private javax.swing.JSpinner fiveCentsSp;
    private javax.swing.JSpinner fiveDollarsSp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner oneCentSp;
    private javax.swing.JSpinner oneDolarCoinSp;
    private javax.swing.JSpinner oneDollarSp;
    private javax.swing.JSpinner oneHundredDollarsSp;
    private javax.swing.JTextField outflowTotalTxt;
    private javax.swing.JTextField reicivableTotalTxt;
    private javax.swing.JTextField sysCashInittxt;
    private javax.swing.JTextField sysCashtxt;
    private javax.swing.JTextField sysChekstxt;
    private javax.swing.JTextField sysCreditCardtxt;
    private javax.swing.JTextField sysDebitCardtxt;
    private javax.swing.JTextField sysInflowTotalTxt;
    private javax.swing.JSpinner tenCentsSp;
    private javax.swing.JSpinner tenDollarsSp;
    private javax.swing.JSpinner twentyDollarsSp;
    private javax.swing.JSpinner twentyFiveCentsSp;
    // End of variables declaration//GEN-END:variables
}
