package views;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class PersonPanel extends javax.swing.JPanel {

    private ImageIcon ic;
    private String address;
    
    public PersonPanel(String dir) {
        address = dir;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newClientJB = new javax.swing.JButton();
        editClientJB = new javax.swing.JButton();
        deleteClientJB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchClientButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        employeeBt = new javax.swing.JButton();

        setBackground(new java.awt.Color(50, 153, 187));
        setName("Client"); // NOI18N
        setPreferredSize(new java.awt.Dimension(692, 529));

        newClientJB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/newClientButtonIcon.png"))); // NOI18N
        newClientJB.setToolTipText("Nuevo Cliente");
        newClientJB.setBorderPainted(false);
        newClientJB.setContentAreaFilled(false);
        newClientJB.setPreferredSize(new java.awt.Dimension(119, 103));
        newClientJB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/newClientButtonIconHover.png"))); // NOI18N
        newClientJB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/newClientButtonIconHover.png"))); // NOI18N
        newClientJB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newClientJBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newClientJBMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newClientJBMouseReleased(evt);
            }
        });
        newClientJB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                newClientJBStateChanged(evt);
            }
        });
        newClientJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newClientJBActionPerformed(evt);
            }
        });

        editClientJB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/editClientButtonIcon.png"))); // NOI18N
        editClientJB.setToolTipText("Editar Cliente");
        editClientJB.setBorderPainted(false);
        editClientJB.setContentAreaFilled(false);
        editClientJB.setPreferredSize(new java.awt.Dimension(119, 103));
        editClientJB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/editClientButtonIconHover.png"))); // NOI18N
        editClientJB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/editClientButtonIconHover.png"))); // NOI18N
        editClientJB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editClientJBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editClientJBMouseExited(evt);
            }
        });
        editClientJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClientJBActionPerformed(evt);
            }
        });

        deleteClientJB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/removeClientButtonIcon.png"))); // NOI18N
        deleteClientJB.setToolTipText("Eliminar Cliente");
        deleteClientJB.setBorderPainted(false);
        deleteClientJB.setContentAreaFilled(false);
        deleteClientJB.setPreferredSize(new java.awt.Dimension(119, 103));
        deleteClientJB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/removeClientButtonIconHover.png"))); // NOI18N
        deleteClientJB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/removeClientButtonIconHover.png"))); // NOI18N
        deleteClientJB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteClientJBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteClientJBMouseExited(evt);
            }
        });
        deleteClientJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClientJBActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/eyetiveLogoBig.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(232, 242));

        searchClientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/searchClientButtonIcon.png"))); // NOI18N
        searchClientButton.setToolTipText("Buscar Cliente");
        searchClientButton.setBorderPainted(false);
        searchClientButton.setContentAreaFilled(false);
        searchClientButton.setPreferredSize(new java.awt.Dimension(119, 103));
        searchClientButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/searchClientButtonIconHover.png"))); // NOI18N
        searchClientButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/searchClientButtonIconHover.png"))); // NOI18N
        searchClientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchClientButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchClientButtonMouseExited(evt);
            }
        });
        searchClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchClientButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/eyetiveLogo.png"))); // NOI18N
        jLabel2.setToolTipText("EYETIVE Agencia Creativa Digital");

        employeeBt.setText("Empleados");
        employeeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newClientJB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editClientJB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteClientJB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(employeeBt)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(newClientJB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(employeeBt)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editClientJB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteClientJB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
	public void paintComponent(Graphics g){
		super.paintComponent(g);
		ic=new ImageIcon(getClass().getResource(getAddress()));
		g.drawImage(ic.getImage(),0,0,this.getWidth(),this.getHeight(),this);
	}
    
    private void newClientJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newClientJBActionPerformed
        // TODO add your handling code here:        
        new PersonView(null, true, 1).setVisible(true);
    }//GEN-LAST:event_newClientJBActionPerformed

    private void editClientJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClientJBActionPerformed
        // TODO add your handling code here:
        new PersonSearchView(null, true,2).setVisible(true);
    }//GEN-LAST:event_editClientJBActionPerformed

    private void deleteClientJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClientJBActionPerformed
        // TODO add your handling code here:
        new PersonSearchView(null, true,3).setVisible(true);
    }//GEN-LAST:event_deleteClientJBActionPerformed

    private void newClientJBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newClientJBMouseEntered
        // TODO add your handling code here:
        //jLabel1.setIcon("HOLA");
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/newClientBigLogo.png")));
    }//GEN-LAST:event_newClientJBMouseEntered

    private void newClientJBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newClientJBMouseExited
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/eyetiveLogoBig.png")));
    }//GEN-LAST:event_newClientJBMouseExited

    private void newClientJBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_newClientJBStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_newClientJBStateChanged

    private void newClientJBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newClientJBMouseReleased
        // TODO add your handling code here:
         
    }//GEN-LAST:event_newClientJBMouseReleased

    private void editClientJBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editClientJBMouseEntered
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/editClientBigLogo.png")));
    }//GEN-LAST:event_editClientJBMouseEntered

    private void deleteClientJBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteClientJBMouseEntered
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/removeClientBigLogo.png")));
    }//GEN-LAST:event_deleteClientJBMouseEntered

    private void editClientJBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editClientJBMouseExited
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/eyetiveLogoBig.png")));
    }//GEN-LAST:event_editClientJBMouseExited

    private void deleteClientJBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteClientJBMouseExited
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/eyetiveLogoBig.png")));
    }//GEN-LAST:event_deleteClientJBMouseExited

    private void searchClientButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchClientButtonMouseEntered
        // TODO add your handling code here:
        
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/searchClientBigLogo.png")));
    }//GEN-LAST:event_searchClientButtonMouseEntered

    private void searchClientButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchClientButtonMouseExited
        // TODO add your handling code here:
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/eyetiveLogoBig.png")));
    }//GEN-LAST:event_searchClientButtonMouseExited

    private void searchClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchClientButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "FUNCIÓN SERÁ AÑADIDA PRÓXIMAMENTE");
    }//GEN-LAST:event_searchClientButtonActionPerformed

    private void employeeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtActionPerformed
        // TODO add your handling code here:
        new EmployeeView(null, true).setVisible(true);
    }//GEN-LAST:event_employeeBtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteClientJB;
    private javax.swing.JButton editClientJB;
    private javax.swing.JButton employeeBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton newClientJB;
    private javax.swing.JButton searchClientButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the address
     */
    public String getAddress() {
        return address;
    }

    /**
     * @param address the address to set
     */
    public void setAddress(String address) {
        this.address = address;
    }
}
