/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.resources.GeneralParameter;
import controller.resources.Operaciones;
import controller.resources.Report;
import controller.service.InvoiceService;
import controller.service.QuotationService;
import controller.service.WorkOrderService;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import views.tableModel.DetailTableModel;
import views.tableModel.QuotationTableModel;
import views.tableModel.WorkDiaryTableModel;

/**
 *
 * @author Jhoe
 */
public class SearchQuotationView extends javax.swing.JDialog {

    private final WorkOrderService workOrderService;
    private final WorkDiaryTableModel workDiaryTableModel;
    private final InvoiceService invoiceService;
    private final QuotationService quotationService;
    private final DetailTableModel detailTableModel;
    private final QuotationTableModel quotationTableModel;
    private final Double auxTot;

    public SearchQuotationView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.workOrderService = new WorkOrderService();
        this.workDiaryTableModel = new WorkDiaryTableModel();
        this.invoiceService = new InvoiceService();
        this.detailTableModel = new DetailTableModel();
        this.quotationService = new QuotationService();
        this.quotationTableModel = new QuotationTableModel();
        this.auxTot = Math.pow(10, GeneralParameter.ACCURACY_VALUE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchQuotationButtonGroup = new javax.swing.ButtonGroup();
        searchQuotationTablePopupOptions = new javax.swing.JPopupMenu();
        showQuotationViewMenuItem = new javax.swing.JMenuItem();
        workOrderGenerateMenuItem = new javax.swing.JMenuItem();
        invoiceGenerateMenuItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchQuotationTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        customerFilterRb = new javax.swing.JRadioButton();
        QuotationNumberRb = new javax.swing.JRadioButton();
        searchQuotationBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchQuotationTable = new javax.swing.JTable();

        showQuotationViewMenuItem.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        showQuotationViewMenuItem.setText("Visualizar Proforma");
        showQuotationViewMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showQuotationViewMenuItemActionPerformed(evt);
            }
        });
        searchQuotationTablePopupOptions.add(showQuotationViewMenuItem);

        workOrderGenerateMenuItem.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        workOrderGenerateMenuItem.setText("Generar Orden de Trabajo");
        workOrderGenerateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workOrderGenerateMenuItemActionPerformed(evt);
            }
        });
        searchQuotationTablePopupOptions.add(workOrderGenerateMenuItem);

        invoiceGenerateMenuItem.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        invoiceGenerateMenuItem.setText("Generar Factura");
        invoiceGenerateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceGenerateMenuItemActionPerformed(evt);
            }
        });
        searchQuotationTablePopupOptions.add(invoiceGenerateMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Proforma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel1.setText("Criterio:");

        searchQuotationTxt.setEnabled(false);
        searchQuotationTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchQuotationTxtActionPerformed(evt);
            }
        });
        searchQuotationTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchQuotationTxtKeyReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 11), new java.awt.Color(0, 153, 255))); // NOI18N

        customerFilterRb.setBackground(new java.awt.Color(255, 255, 255));
        searchQuotationButtonGroup.add(customerFilterRb);
        customerFilterRb.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        customerFilterRb.setText("Cliente");
        customerFilterRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerFilterRbActionPerformed(evt);
            }
        });

        QuotationNumberRb.setBackground(new java.awt.Color(255, 255, 255));
        searchQuotationButtonGroup.add(QuotationNumberRb);
        QuotationNumberRb.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        QuotationNumberRb.setSelected(true);
        QuotationNumberRb.setText("Nro. Proforma");
        QuotationNumberRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuotationNumberRbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuotationNumberRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerFilterRb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(QuotationNumberRb))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(customerFilterRb)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        searchQuotationBt.setText("Buscar");
        searchQuotationBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchQuotationBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchQuotationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchQuotationBt, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchQuotationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchQuotationBt))
                .addGap(73, 73, 73))
        );

        searchQuotationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        searchQuotationTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchQuotationTableMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchQuotationTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(searchQuotationTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchQuotationTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchQuotationTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchQuotationTxtActionPerformed

    private void searchQuotationBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchQuotationBtActionPerformed
        // TODO add your handling code here:

        if (QuotationNumberRb.isSelected()) {
            chargeQuotationTable();
        }

    }//GEN-LAST:event_searchQuotationBtActionPerformed

    private void customerFilterRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerFilterRbActionPerformed
        // TODO add your handling code here:
        if (customerFilterRb.isSelected()) {
            searchQuotationTxt.setEnabled(true);
            searchQuotationBt.setEnabled(false);
        }
    }//GEN-LAST:event_customerFilterRbActionPerformed

    private void searchQuotationTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchQuotationTxtKeyReleased
        // TODO add your handling code here:
        chargeQuotationTable();

    }//GEN-LAST:event_searchQuotationTxtKeyReleased

    private void searchQuotationTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchQuotationTableMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 1){
            //Cuando el usuario selecciona una fila de la tabla fijamos la instancia de la orden de trabajo
            
        }
    }//GEN-LAST:event_searchQuotationTableMouseClicked

    private void searchQuotationTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchQuotationTableMousePressed
        // TODO add your handling code here:          
        tableOptionsPopup(evt);
    }//GEN-LAST:event_searchQuotationTableMousePressed

    private void chargeWorkOrderData(){
        
        this.workOrderService.getWorkOrder().setWorkOrderState(1);
        this.workOrderService.getWorkOrder().setWorkOrderType("WorkOrder");
        this.workOrderService.getWorkOrder().setWorkOrderPriority(0);
        this.workOrderService.getWorkOrder().setWorkOrderDescription("Trabajo de impresión");
        this.workOrderService.getWorkOrder().setWorkOrderNumber(String.valueOf(GeneralParameter.WORK_ORDER_NUMBER + 1));
        this.workOrderService.getWorkOrder().setWorkOrderDeliveryDate(new Date());
        this.workOrderService.getWorkOrder().setWorkOrderTotal(0.00);
        this.workOrderService.getWorkOrder().setWorkOrderBalance(0.00);
        this.workOrderService.getWorkOrder().setWorkOrderAdvance(0.00);
        this.workOrderService.getWorkOrder().setWorkOrderSubtotal(this.quotationService.getQuotation().getQuotationSubtotal());
        this.workOrderService.getWorkOrder().setWorkOrderIva(this.quotationService.getQuotation().getQuotationIva());
        this.workOrderService.getWorkOrder().setWorkOrderTotal(this.quotationService.getQuotation().getQuotationTotal());
        this.workOrderService.getWorkOrder().setWorkOrderChange(0.00);
        this.workOrderService.getWorkOrder().setWorkOrderCash(0.00);
        
        //this.workOrderService.getWorkOrder().setDetailList(this.quotationService.getQuotation().getDetailList());
        this.quotationDetailToWorkOrderDetail();
        
        this.workOrderService.getWorkOrder().setPerson(this.quotationService.getQuotation().getPerson());
     
    }
    
    private void chargeWorkOrderView(){
        
    }
    
    private void chargeInvoiceData() {
        
        if(this.quotationService.getQuotation().getQuotationTotal() == 0.00 || this.quotationService.getQuotation().getQuotationTotal() == null){
            this.invoiceIvaCalculate();
        }else{
            this.invoiceService.getInvoice().setInSubtotal(this.quotationService.getQuotation().getQuotationSubtotal());
            this.invoiceService.getInvoice().setInSubtotalIvazero(0.00);
            this.invoiceService.getInvoice().setInSubtotalIva(this.quotationService.getQuotation().getQuotationSubtotal());
            this.invoiceService.getInvoice().setInIva(this.quotationService.getQuotation().getQuotationIva());
            this.invoiceService.getInvoice().setInTotal(this.quotationService.getQuotation().getQuotationTotal());
            this.invoiceService.getInvoice().setInCash(0.00);
            this.invoiceService.getInvoice().setInChange(0.00);
        }
        
        this.invoiceService.getInvoice().setInIssueDate(new Date());
        this.invoiceService.getInvoice().setInIssueTime(new Date());
        this.invoiceService.getInvoice().setInNumber("" + (Integer.valueOf(GeneralParameter.THIRD_INVOICE_NUMBRE) + 1));
        this.invoiceService.getInvoice().setInState("Realizada");
        this.invoiceService.getInvoice().setPerson(this.quotationService.getQuotation().getPerson());

        this.quotationDetailToInvoiceDetail();
        //this.invoiceService.getInvoice().setDetailList(this.workOrderService.getWorkOrder().getDetailList());

    }

    //Actualizamos el tipo de detalle de oreden de trabajo a factura
    private void quotationDetailToInvoiceDetail() {

        this.invoiceService.getInvoice().setDetailList(this.quotationService.getQuotation().getDetailList());
        
        for (int i = 0; i < this.invoiceService.getInvoice().getDetailList().size(); i++) {
            this.invoiceService.getInvoice().getDetailList().get(i).setDetType("InvoiceDetail");
            this.invoiceService.getInvoice().getDetailList().get(i).setWorkOrder(null);
            this.invoiceService.getInvoice().getDetailList().get(i).setDetailId(null);
            this.invoiceService.getInvoice().getDetailList().get(i).setInvoice(this.invoiceService.getInvoice());
        }
    }
    
    private void quotationDetailToWorkOrderDetail(){
        this.workOrderService.getWorkOrder().setDetailList(this.quotationService.getQuotation().getDetailList());
        
        for (int i = 0; i < this.workOrderService.getWorkOrder().getDetailList().size(); i++) {
            this.workOrderService.getWorkOrder().getDetailList().get(i).setDetType("WorkOrderDetail");
            this.workOrderService.getWorkOrder().getDetailList().get(i).setQuotation(null);
            this.workOrderService.getWorkOrder().getDetailList().get(i).setDetailId(null);
            this.workOrderService.getWorkOrder().getDetailList().get(i).setWorkOrder(this.workOrderService.getWorkOrder());
        }
    }

    private void showQuotationViewMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showQuotationViewMenuItemActionPerformed
        // TODO add your handling code here:
        //this.workOrderService.setInstance(this.workDiaryTableModel.getList().get(searchQuotationTable.getSelectedRow()));
        //new ReceiptView(null, true, workOrderService).setVisible(true);
        this.detailTableModel.setList(this.quotationService.getQuotation().getDetailList());
        Report report = new Report();
        report.printQuotation(quotationService, this.detailTableModel);
    }//GEN-LAST:event_showQuotationViewMenuItemActionPerformed

    private void invoiceGenerateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceGenerateMenuItemActionPerformed
        // TODO add your handling code here:
        //Generar una factura a partir de una orden de trabajo
        chargeInvoiceData();
        //if (this.invoiceService.getInvoice().getInvoiceId() == null) {
            if (this.invoiceService.saveInvoice()) {
                JOptionPane.showMessageDialog(null, "La factura ha sido generada correctamente");
                Report report = new Report();
                this.detailTableModel.setList(this.invoiceService.getInvoice().getDetailList());
                report.printInvoice(invoiceService, this.detailTableModel);
                //Inicializamos a 0 la orden de trabajo par apoder elegir otra
                this.workOrderService.newInstace();
           // }
        }

    }//GEN-LAST:event_invoiceGenerateMenuItemActionPerformed

    private void QuotationNumberRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuotationNumberRbActionPerformed
        // TODO add your handling code here:
        if (QuotationNumberRb.isSelected()) {
            searchQuotationBt.setEnabled(true);
            searchQuotationTxt.setEnabled(true);
        }
    }//GEN-LAST:event_QuotationNumberRbActionPerformed

    private void workOrderGenerateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workOrderGenerateMenuItemActionPerformed
        // TODO add your handling code here:
        
        chargeWorkOrderData();
        new ReceiptView(null, true, this.workOrderService).setVisible(true);
        
    }//GEN-LAST:event_workOrderGenerateMenuItemActionPerformed

    private void invoiceIvaCalculate() {
        Double subtotal;
        Double iva;
        Double total;
        
        subtotal = this.workOrderService.getWorkOrder().getWorkOrderTotal();
        this.invoiceService.getInvoice().setInSubtotal(subtotal);
        this.invoiceService.getInvoice().setInSubtotalIva(subtotal);
        this.invoiceService.getInvoice().setInSubtotalIvazero(0.00);
        

        iva = this.workOrderService.getWorkOrder().getWorkOrderTotal() * 0.12;
        this.invoiceService.getInvoice().setInIva(Double.valueOf(Operaciones.parteDecimal(Math.rint(iva * auxTot) / auxTot, GeneralParameter.ACCURACY_VALUE)));

        total = this.workOrderService.getWorkOrder().getWorkOrderTotal() + iva;
        this.invoiceService.getInvoice().setInTotal(Double.valueOf(Operaciones.parteDecimal(Math.rint(total * auxTot) / auxTot, GeneralParameter.ACCURACY_VALUE)));

    }

    private void tableOptionsPopup(java.awt.event.MouseEvent evt) {
        if (evt.getButton() == MouseEvent.BUTTON3) {
            Point p = evt.getPoint();
            int rowNumber = searchQuotationTable.rowAtPoint(p);
            ListSelectionModel modelo = searchQuotationTable.getSelectionModel();
            modelo.setSelectionInterval(rowNumber, rowNumber);

            System.out.println("fila presionada " + searchQuotationTable.getSelectedRow());
            //Cargamos una nueva instancia del una orden de trabajo
            this.quotationService.setInstance(this.quotationTableModel.getList().get(this.searchQuotationTable.getSelectedRow()));

            //removeTable.setEnabled(true);
            //addTable.setEnabled(false);
            //changeTableToAnother.setEnabled(true);
            searchQuotationTablePopupOptions.show(evt.getComponent(), evt.getX(), evt.getY());
            searchQuotationTablePopupOptions.setVisible(true);
        }
    }

    private void chargeQuotationTable() {
        if (QuotationNumberRb.isSelected()) {
            this.quotationTableModel.setList(this.quotationService.getQuotationListByNumber(searchQuotationTxt.getText()));
        } else if (this.customerFilterRb.isSelected()) {
            this.quotationTableModel.setList(this.quotationService.getQuotationListByCustomerCriteria(searchQuotationTxt.getText()));
        } //else if (this.dateFilterRb.isSelected()) {
            //this.workDiaryTableModel.setList(this.workOrderService.getWorkOrderListByEmployeeCriteria(searchQuotationTxt.getText()));
        //}

        this.searchQuotationTable.setModel(quotationTableModel);
        this.searchQuotationTable.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton QuotationNumberRb;
    private javax.swing.JRadioButton customerFilterRb;
    private javax.swing.JMenuItem invoiceGenerateMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchQuotationBt;
    private javax.swing.ButtonGroup searchQuotationButtonGroup;
    private javax.swing.JTable searchQuotationTable;
    private javax.swing.JPopupMenu searchQuotationTablePopupOptions;
    private javax.swing.JTextField searchQuotationTxt;
    private javax.swing.JMenuItem showQuotationViewMenuItem;
    private javax.swing.JMenuItem workOrderGenerateMenuItem;
    // End of variables declaration//GEN-END:variables
}
