/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.resources.PanelPersonalizado;
import controller.service.EmployeeService;
import controller.service.RolService;
import controller.service.UserAccountService;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import views.tableModel.EmployeeTableModel;
import views.tableModel.RolComboBoxModel;
import views.tableModel.RolTableModel;
import views.tableModel.UserAccountTableModel;

/**
 *
 * @author Usuario
 */
public class userAdministrationPanel extends javax.swing.JPanel {

    private final UserAccountService uaService;
    private final UserAccountTableModel uatm;
    private final RolTableModel rtm;
    private final RolService rolService;
    private final EmployeeService employeeService;
    private final EmployeeTableModel etm;

    public userAdministrationPanel() {
        this.uaService = new UserAccountService();
        this.uatm = new UserAccountTableModel();
        this.rtm = new RolTableModel();
        this.rolService = new RolService();
        this.employeeService = new EmployeeService();
        this.etm = new EmployeeTableModel();
        initComponents();
        chargeUserAccountTable();
        chargeRolTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchClientTxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        accountNameTxt = new javax.swing.JTextField();
        accountPasswordPtxt = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        accountRepeatPassTxt = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        rolComboBox = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        personNameTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        personAddressTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        personIdentificarionTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        personPhoneTxt = new javax.swing.JTextField();
        rolPanel = new javax.swing.JPanel();
        jPanel3 = new PanelPersonalizado("/images/backgrounds/userAdministratioArmoire.png");
        jPanel2 = new javax.swing.JPanel();
        newUserOrRol = new javax.swing.JButton();
        editUserOrRol = new javax.swing.JButton();
        blockUser = new javax.swing.JButton();
        userHistory = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        adminTabbedPane = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userAccountTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rolTable = new javax.swing.JTable();

        userPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setText("Buscar empleados:");

        searchClientTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchClientTxtActionPerformed(evt);
            }
        });
        searchClientTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchClientTxtKeyReleased(evt);
            }
        });

        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        clientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(clientTable);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Cuenta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setText("Cuenta:");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setText("Contraseña:");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setText("Repetir Contraseña:");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setText("Rol:");

        rolComboBox.setModel(new RolComboBoxModel(this.rolService.listPermitedRol()));
        rolComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolComboBoxActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setText("Nombres:");

        personNameTxt.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel7.setText("Dirección:");

        personAddressTxt.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel8.setText("Identificación:");

        personIdentificarionTxt.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel9.setText("Teléfono:");

        personPhoneTxt.setEditable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(personNameTxt)
                    .addComponent(personAddressTxt)
                    .addComponent(personIdentificarionTxt)
                    .addComponent(personPhoneTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(personNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(personAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(personIdentificarionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(accountNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountPasswordPtxt)
                    .addComponent(accountRepeatPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountPasswordPtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(accountRepeatPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchClientTxt))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchClientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rolPanelLayout = new javax.swing.GroupLayout(rolPanel);
        rolPanel.setLayout(rolPanelLayout);
        rolPanelLayout.setHorizontalGroup(
            rolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        rolPanelLayout.setVerticalGroup(
            rolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(692, 529));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        newUserOrRol.setText("Nuevo");
        newUserOrRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserOrRolActionPerformed(evt);
            }
        });

        editUserOrRol.setText("Editar");
        editUserOrRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserOrRolActionPerformed(evt);
            }
        });

        blockUser.setText("Bloquear");

        userHistory.setText("Historial");
        userHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userHistoryActionPerformed(evt);
            }
        });

        saveButton.setText("Guardar");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newUserOrRol, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editUserOrRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blockUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userHistory)
                .addGap(0, 188, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(blockUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(userHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(editUserOrRol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(newUserOrRol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        userAccountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userAccountTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Usuarios", jPanel4);

        rolTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(rolTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        adminTabbedPane.addTab("Roles", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(adminTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(adminTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newUserOrRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserOrRolActionPerformed
        // TODO add your handling code here:
        if (adminTabbedPane.getSelectedIndex() == 0) {
            adminTabbedPane.addTab("Nuevo usuario", userPanel);
            searchClientTxt.setEnabled(true);
            this.newTabControl();
        } else if (adminTabbedPane.getSelectedIndex() == 1) {
            adminTabbedPane.addTab("Nuevo rol", rolPanel);
            this.newTabControl();
        }
    }//GEN-LAST:event_newUserOrRolActionPerformed

    private void newTabControl() {
        adminTabbedPane.setSelectedIndex(2);
        adminTabbedPane.setEnabledAt(0, false);
        adminTabbedPane.setEnabledAt(1, false);
        saveButton.setEnabled(true);
        editUserOrRol.setEnabled(false);
    }

    private void searchClientTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchClientTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchClientTxtActionPerformed

    private void rolComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolComboBoxActionPerformed

    private void userHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userHistoryActionPerformed

    private void chargeAccountData() {
        this.uaService.getUserAccount().setUsrName(accountNameTxt.getText());
        this.uaService.getUserAccount().setUsrPassword(accountPasswordPtxt.getText());
        if (adminTabbedPane.getTitleAt(2).equals("Nuevo usuario")) {
            this.uaService.getUserAccount().setEmployee(this.employeeService.getEmployee());
        }
        this.uaService.getUserAccount().setRol(this.rolService.listPermitedRol().get(rolComboBox.getSelectedIndex()));
    }

    private void chargeAccountView() {
        this.uaService.setInstance(this.uatm.getList().get(userAccountTable.getSelectedRow()));
        accountNameTxt.setText(this.uaService.getUserAccount().getUsrName());
        accountPasswordPtxt.setText(this.uaService.getUserAccount().getUsrPassword());
        accountRepeatPassTxt.setText(this.uaService.getUserAccount().getUsrPassword());
        rolComboBox.setSelectedItem(this.uaService.getUserAccount().getRol());

        personNameTxt.setText(this.uaService.getUserAccount().getEmployee().toString());
        personAddressTxt.setText(this.uaService.getUserAccount().getEmployee().getEmployeeAddress());
        personIdentificarionTxt.setText(this.uaService.getUserAccount().getEmployee().getEmployeeIdentification());
        personPhoneTxt.setText(this.uaService.getUserAccount().getEmployee().getEmployeePhone());
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:

        if (adminTabbedPane.getTitleAt(2).equals("Nuevo usuario") || adminTabbedPane.getTitleAt(2).equals("Editar usuario")) {

            if (this.uaService.getUserAccount().getUserAccountId() == null) {
                this.chargeAccountData();
                if (this.uaService.saveUserAccount()) {
                    JOptionPane.showMessageDialog(this, "Cuenta guardada correctamente");
                    adminTabbedPane.setSelectedIndex(0);
                    this.saveTabControl();
                    this.clearFields();
                    this.chargeUserAccountTable();
                }
            } else if (this.uaService.getUserAccount().getUserAccountId() != null) {
                this.chargeAccountData();
                if (this.uaService.editUserAccount()) {
                    JOptionPane.showMessageDialog(this, "Cuenta modificada correctamente");
                    adminTabbedPane.setSelectedIndex(0);
                    this.saveTabControl();
                    this.clearFields();
                    userAccountTable.updateUI();
                }
            }
        } else {
            adminTabbedPane.setSelectedIndex(1);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void clearFields() {
        searchClientTxt.setText("");
        clientTable.setModel(new DefaultTableModel());
        //this.ptm.setList(null);
        accountNameTxt.setText("");
        accountPasswordPtxt.setText("");
        accountRepeatPassTxt.setText("");
        rolComboBox.setSelectedItem("");
        personNameTxt.setText("");
        personAddressTxt.setText("");
        personIdentificarionTxt.setText("");
        personPhoneTxt.setText("");
        this.uaService.newInstance();
        this.rolService.newInstance();
    }

    private void saveTabControl() {
        adminTabbedPane.setEnabledAt(0, true);
        adminTabbedPane.setEnabledAt(1, true);
        adminTabbedPane.remove(2);
        saveButton.setEnabled(false);
        newUserOrRol.setEnabled(true);
        editUserOrRol.setEnabled(true);
        userAccountTable.clearSelection();
        rolTable.clearSelection();
    }

    private void editTabControl() {
        adminTabbedPane.setSelectedIndex(2);
        adminTabbedPane.setEnabledAt(0, false);
        adminTabbedPane.setEnabledAt(1, false);
        saveButton.setEnabled(true);
        newUserOrRol.setEnabled(false);
    }

    private void editUserOrRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserOrRolActionPerformed
        // TODO add your handling code here:
        if (userAccountTable.getSelectedRow() >= 0 || rolTable.getSelectedRow() >= 0) {
            if (adminTabbedPane.getSelectedIndex() == 0) {
                adminTabbedPane.addTab("Editar usuario", userPanel);
                searchClientTxt.setEnabled(false);
                this.chargeAccountView();
                this.editTabControl();
            } else if (adminTabbedPane.getSelectedIndex() == 1) {
                adminTabbedPane.addTab("Editar rol", rolPanel);
                this.editTabControl();
            }

        } else {
            JOptionPane.showMessageDialog(this, "No ha seleccionado ningún dato");
        }
    }//GEN-LAST:event_editUserOrRolActionPerformed

    private void searchClientTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchClientTxtKeyReleased
        // TODO add your handling code here:
        this.etm.setList(this.employeeService.getEmployeesByCriteria(searchClientTxt.getText()));
        this.clientTable.setModel(this.etm);
        this.clientTable.updateUI();
    }//GEN-LAST:event_searchClientTxtKeyReleased

    private void chargeEmployeePersonalData() {
        personNameTxt.setText(this.employeeService.getEmployee().toString());
        personAddressTxt.setText(this.employeeService.getEmployee().getEmployeeAddress());
        personIdentificarionTxt.setText(this.employeeService.getEmployee().getEmployeeIdentification());
        personPhoneTxt.setText(this.employeeService.getEmployee().getEmployeePhone());
    }

    private void clientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientTableMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.employeeService.setInstance(this.etm.getList().get(clientTable.getSelectedRow()));
            this.chargeEmployeePersonalData();
        }
    }//GEN-LAST:event_clientTableMouseClicked

    private void chargeUserAccountTable() {
        this.uatm.setList(this.uaService.list());
        this.userAccountTable.setModel(uatm);
        this.userAccountTable.updateUI();
    }

    private void chargeRolTable() {
        this.rtm.setList(this.rolService.list());
        this.rolTable.setModel(rtm);
        this.rolTable.updateUI();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNameTxt;
    private javax.swing.JPasswordField accountPasswordPtxt;
    private javax.swing.JPasswordField accountRepeatPassTxt;
    private javax.swing.JTabbedPane adminTabbedPane;
    private javax.swing.JButton blockUser;
    private javax.swing.JTable clientTable;
    private javax.swing.JButton editUserOrRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton newUserOrRol;
    private javax.swing.JTextField personAddressTxt;
    private javax.swing.JTextField personIdentificarionTxt;
    private javax.swing.JTextField personNameTxt;
    private javax.swing.JTextField personPhoneTxt;
    private javax.swing.JComboBox rolComboBox;
    private javax.swing.JPanel rolPanel;
    private javax.swing.JTable rolTable;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField searchClientTxt;
    private javax.swing.JTable userAccountTable;
    private javax.swing.JButton userHistory;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables
}
