/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controller.resources.GeneralParameter;
import controller.resources.Operaciones;
import controller.service.DetailService;
import controller.service.EmployeeService;
import controller.service.PersonService;
import controller.service.WorkOrderService;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import views.tableModel.DetailTableModel;
import views.tableModel.EmployeeComboBoxModel;
import views.tableModel.PersonComboBoxModel;

/**
 *
 * @author Usuario
 */
public class WorkOrderView extends javax.swing.JDialog {

    private final DetailService ds;
    private final PersonService pns;
    private final WorkOrderService wos;
    private final DetailTableModel dtm;
    private final EmployeeService employeeService;
    private JTextField searchNameText;
    private final Double auxTot;

    public WorkOrderView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.ds = new DetailService();
        this.pns = new PersonService();
        this.wos = new WorkOrderService();
        this.dtm = new DetailTableModel();
        this.employeeService = new EmployeeService();
        
        initComponents();
        this.auxTot = Math.pow(10, GeneralParameter.ACCURACY_VALUE);
        this.chargePersonCombo();
        this.chargeEmployeeCombo();
    }

    public WorkOrderView(java.awt.Frame parent, boolean modal, WorkOrderService wos) {
        super(parent, modal);
        this.ds = new DetailService();
        this.pns = new PersonService();
        //this.wos = new WorkOrderService();
        this.dtm = new DetailTableModel();
        this.employeeService = new EmployeeService();
        initComponents();
        this.auxTot = Math.pow(10, GeneralParameter.ACCURACY_VALUE);
        this.wos = wos;
        this.chargePersonCombo();
        this.chargeEmployeeCombo();
        this.chargeWorkOrderView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        pruebaJC = new javax.swing.JComboBox();
        add = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        workOrderTotalTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        workOrderAdvanceTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        workOrderBalanceTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workOrderDetailTable = new javax.swing.JTable();
        workOrderAddBt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        workOrderNumberTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        workOrderIssueDc = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        workOrderDeliveryDc = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        workOrderStateCb = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        searchNameComboText = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        workOrderPersonNameTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        workOrderPersonLastNameTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        workOrderPersonIdentificationTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        workOrderPersonPhoneTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        workOrderPersonAddressTxt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        employeeComboBox = new javax.swing.JComboBox();
        workOrderCancelBt = new javax.swing.JButton();
        workOrderSaveBt = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        workOrderHightPriorityJrb = new javax.swing.JRadioButton();
        workOrderNormalPriorityJrb = new javax.swing.JRadioButton();
        workOrderLowPriorityJrb = new javax.swing.JRadioButton();

        pruebaJC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        add.setText("jButton1");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(pruebaJC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(add)
                .addContainerGap(439, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pruebaJC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add))
                .addContainerGap(495, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("VALOR:");

        workOrderTotalTxt.setEditable(false);
        workOrderTotalTxt.setText("0.00");
        workOrderTotalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workOrderTotalTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ANTICIPO:");

        workOrderAdvanceTxt.setText("0.00");
        workOrderAdvanceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workOrderAdvanceTxtActionPerformed(evt);
            }
        });
        workOrderAdvanceTxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                workOrderAdvanceTxtPropertyChange(evt);
            }
        });
        workOrderAdvanceTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                workOrderAdvanceTxtKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("SALDO:");

        workOrderBalanceTxt.setText("0.00");
        workOrderBalanceTxt.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(workOrderTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workOrderAdvanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workOrderBalanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(workOrderBalanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(workOrderAdvanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(workOrderTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        workOrderDetailTable.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        workOrderDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(workOrderDetailTable);

        workOrderAddBt.setText("AÑADIR");
        workOrderAddBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workOrderAddBtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("DETALLE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(workOrderAddBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workOrderAddBt)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ORDEN DE TRABAJO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 153, 255))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Número:");

        workOrderNumberTxt.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        workOrderNumberTxt.setForeground(new java.awt.Color(255, 51, 51));
        workOrderNumberTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        workOrderNumberTxt.setText("000000023");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Fecha de recepción:");

        workOrderIssueDc.setBackground(new java.awt.Color(255, 255, 255));
        workOrderIssueDc.setDate(new Date());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Fecha de entrega:");

        workOrderDeliveryDc.setBackground(new java.awt.Color(255, 255, 255));
        workOrderDeliveryDc.setDate(new Date());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Estado:");

        workOrderStateCb.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        workOrderStateCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDIENTE", "PAUSADO", "TERMINADO" }));
        workOrderStateCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workOrderStateCbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workOrderStateCb, 0, 1, Short.MAX_VALUE)
                    .addComponent(workOrderDeliveryDc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(workOrderNumberTxt)
                    .addComponent(workOrderIssueDc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(workOrderStateCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workOrderNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(workOrderIssueDc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(workOrderDeliveryDc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(12, 12, 12))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 153, 255))); // NOI18N

        searchNameComboText.setEditable(true);
        searchNameComboText.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                searchNameComboTextPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        searchNameComboText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNameComboTextActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Buscar:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Nombre:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Apellido:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Identificación:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Teléfono:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Dirección:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(workOrderPersonNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(workOrderPersonIdentificationTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(workOrderPersonLastNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(workOrderPersonPhoneTxt)))
                    .addComponent(workOrderPersonAddressTxt)
                    .addComponent(searchNameComboText, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchNameComboText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(workOrderPersonNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workOrderPersonLastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workOrderPersonIdentificationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workOrderPersonPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workOrderPersonAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESPONSABLE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 153, 255))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Será realizada por:");

        employeeComboBox.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        employeeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciones un empleado...", "Julio Galán ", "Israel Sotomayor" }));
        employeeComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                employeeComboBoxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeComboBox, 0, 340, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(employeeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        workOrderCancelBt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        workOrderCancelBt.setText("CANCELAR");
        workOrderCancelBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workOrderCancelBtActionPerformed(evt);
            }
        });

        workOrderSaveBt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        workOrderSaveBt.setText("GUARDAR");
        workOrderSaveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workOrderSaveBtActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Prioridad:");

        workOrderHightPriorityJrb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(workOrderHightPriorityJrb);
        workOrderHightPriorityJrb.setText("Alta");

        workOrderNormalPriorityJrb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(workOrderNormalPriorityJrb);
        workOrderNormalPriorityJrb.setText("Media");

        workOrderLowPriorityJrb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(workOrderLowPriorityJrb);
        workOrderLowPriorityJrb.setText("Baja");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(workOrderHightPriorityJrb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(workOrderNormalPriorityJrb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workOrderLowPriorityJrb)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workOrderHightPriorityJrb)
                    .addComponent(jLabel15)
                    .addComponent(workOrderNormalPriorityJrb)
                    .addComponent(workOrderLowPriorityJrb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(workOrderSaveBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(workOrderCancelBt))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(workOrderCancelBt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(workOrderSaveBt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void workOrderAddBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workOrderAddBtActionPerformed
        // TODO add your handling code here:
        new WorkOrderItemView(null, true, this, this.pns.getPerson().getPrType()).setVisible(true);

        if (this.ds.getDetail().getDetTotal() != null) {
            workOrderTotalTxt.setText(String.valueOf(Operaciones.parteDecimal(Math.rint(this.ds.getDetail().getDetTotal() * auxTot) / auxTot, GeneralParameter.ACCURACY_VALUE)));
            this.ds.getDetail().setWorkOrder(this.wos.getWorkOrder());
            this.ds.addDetailList(this.ds.getDetail());
            this.updateWorkOrderDetailTable();
        }

    }//GEN-LAST:event_workOrderAddBtActionPerformed
    //Cargamos o actualizamos los datos de la lista detalle en la tabla
    private void updateWorkOrderDetailTable() {
        this.dtm.setList(this.ds.getDetailList());
        this.workOrderDetailTable.setModel(this.dtm);
        this.workOrderDetailTable.updateUI();
    }

    //Cargamos una instancia del detalle del dialogo WorkOrderItemView y creamos una nueva instancia del detalle 
    public void getWorkItemDetail(DetailService detailService) {
        this.ds.setIntance(detailService.getDetail());
    }
    
    private void chargeEmployeeCombo(){
    employeeComboBox.setModel(new EmployeeComboBoxModel(this.employeeService.list()));
    employeeComboBox.setSelectedIndex(0);
}

    private void chargePersonCombo() {

        searchNameText = (JTextField) searchNameComboText.getComponent(2);
        searchNameText.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent evt) {
                if (evt.getKeyCode() == 27) {
                    searchNameComboText.setPopupVisible(false);
                    return;
                }
                if (evt.getKeyCode() == 10) {
                    if (searchNameComboText.getSelectedIndex() != - 1) {
                        PersonComboBoxModel pcm = (PersonComboBoxModel) searchNameComboText.getModel();
                        pns.setInstance(pcm.getSelectedItem());
                        chargePersonView();
                    }
                    searchNameComboText.setPopupVisible(false);
                    return;
                }

                if (evt.getKeyCode() == 40 || evt.getKeyCode() == 39 || evt.getKeyCode() == 38 || evt.getKeyCode() == 37
                        || evt.getKeyCode() == 36 || evt.getKeyCode() == 16 || evt.getKeyCode() == 35) {
                    return;
                }

                int position = searchNameText.getCaretPosition();
                String s = searchNameText.getText();
                searchNameComboText.setModel(new PersonComboBoxModel(pns.getPersonsByCriteriaType(searchNameText.getText())));
                searchNameText.setText(s);

                searchNameText.setCaretPosition(position);
                searchNameComboText.setPopupVisible(true);
            }
        });
    }

    private void chargePersonView() {
        workOrderPersonNameTxt.setText(this.pns.getPerson().getPrFirstName());
        workOrderPersonLastNameTxt.setText(this.pns.getPerson().getPrLastName());
        workOrderPersonIdentificationTxt.setText(this.pns.getPerson().getPrIdentification());
        workOrderPersonPhoneTxt.setText((this.pns.getPerson().getPrPhone()));
        workOrderPersonAddressTxt.setText(this.pns.getPerson().getPrAddress());
    }

    private void chargeWorkOrderData() {
        this.wos.getWorkOrder().setWorkOrderDescription("Prueba");
        if (this.workOrderStateCb.getSelectedItem().equals("PENDIENTE")) {
            this.wos.getWorkOrder().setWorkOrderState(1);
        } else if (this.workOrderStateCb.getSelectedItem().equals("PAUSADO")) {
            this.wos.getWorkOrder().setWorkOrderState(2);
        } else if (this.workOrderStateCb.getSelectedItem().equals("TERMINADO")) {
            this.wos.getWorkOrder().setWorkOrderState(3);
        }
        this.wos.getWorkOrder().setWorkOrderNumber(workOrderNumberTxt.getText());
        this.wos.getWorkOrder().setWorkOrderIssueDate(workOrderIssueDc.getDate());
        this.wos.getWorkOrder().setWorkOrderDeliveryDate(workOrderDeliveryDc.getDate());
        this.wos.getWorkOrder().setWorkOrderTotal(Double.valueOf(workOrderTotalTxt.getText()));
        this.wos.getWorkOrder().setWorkOrderAdvance(Double.valueOf(workOrderAdvanceTxt.getText()));
        this.wos.getWorkOrder().setWorkOrderBalance(Double.valueOf(workOrderBalanceTxt.getText()));
        
        if(this.workOrderLowPriorityJrb.isSelected()){
            this.wos.getWorkOrder().setWorkOrderPriority(0);
        }else if(this.workOrderNormalPriorityJrb.isSelected()){
            this.wos.getWorkOrder().setWorkOrderPriority(1);
        }else if(this.workOrderHightPriorityJrb.isSelected()){
            this.wos.getWorkOrder().setWorkOrderPriority(2);
        }

        this.wos.getWorkOrder().setDetailList(this.ds.getDetailList());

        this.wos.getWorkOrder().setPerson(this.pns.getPerson());
        this.wos.getWorkOrder().setEmployee(this.employeeService.getEmployee());

    }

    private void chargeWorkOrderView() {
        if (null != this.wos.getWorkOrder().getWorkOrderState()) {
            switch (this.wos.getWorkOrder().getWorkOrderState()) {
                case 1:
                    this.workOrderStateCb.setSelectedItem("PENDIENTE");
                    break;
                case 2:
                    this.workOrderStateCb.setSelectedItem("PAUSADO");
                    break;
                case 3:
                    this.workOrderStateCb.setSelectedItem("TERMINADO");
                    break;
                default:
                    break;
            }
        }

        this.workOrderNumberTxt.setText(this.wos.getWorkOrder().getWorkOrderNumber());
        this.workOrderIssueDc.setDate(this.wos.getWorkOrder().getWorkOrderIssueDate());
        this.workOrderDeliveryDc.setDate(this.wos.getWorkOrder().getWorkOrderDeliveryDate());
        this.pns.setInstance(this.wos.getWorkOrder().getPerson());
        this.chargePersonView();
        
        this.employeeComboBox.setSelectedItem(this.wos.getWorkOrder().getEmployee());
        
        if(null != this.wos.getWorkOrder().getWorkOrderPriority())switch (this.wos.getWorkOrder().getWorkOrderPriority()) {
            case 0:
                this.workOrderLowPriorityJrb.setSelected(true);
                break;
            case 1:
                this.workOrderNormalPriorityJrb.setSelected(true);
                break;
            case 2:
                this.workOrderHightPriorityJrb.setSelected(true);
                break;
            default:
                break;
        }
        this.workOrderTotalTxt.setText(String.valueOf(this.wos.getWorkOrder().getWorkOrderTotal()));
        this.workOrderBalanceTxt.setText(String.valueOf(this.wos.getWorkOrder().getWorkOrderBalance()));
        this.workOrderAdvanceTxt.setText(String.valueOf(this.wos.getWorkOrder().getWorkOrderAdvance()));

        this.ds.setDetailList(this.wos.getWorkOrder().getDetailList());
        this.updateWorkOrderDetailTable();
    }


    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        workOrderPersonAddressTxt.setText(pruebaJC.getSelectedItem().toString());
    }//GEN-LAST:event_addActionPerformed

    private void workOrderTotalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workOrderTotalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workOrderTotalTxtActionPerformed

    private void searchNameComboTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNameComboTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchNameComboTextActionPerformed

    private void searchNameComboTextPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_searchNameComboTextPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (searchNameComboText.getItemCount() != 0) {
            PersonComboBoxModel pcbm = (PersonComboBoxModel) searchNameComboText.getModel();
            this.pns.setInstance(pcbm.getSelectedItem());
            if (this.pns.getPerson() != null) {
                this.chargePersonView();
            }
        }
    }//GEN-LAST:event_searchNameComboTextPopupMenuWillBecomeInvisible

    private void workOrderSaveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workOrderSaveBtActionPerformed
        // TODO add your handling code here:
        if (this.wos.getWorkOrder().getWorkOrderId() == null) {
            this.chargeWorkOrderData();
            if (this.wos.saveWorkOrder()) {
                JOptionPane.showMessageDialog(this, "La orden de trabajo ha sido guardada correctamente");
            }
        }
    }//GEN-LAST:event_workOrderSaveBtActionPerformed

    private void workOrderStateCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workOrderStateCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workOrderStateCbActionPerformed

    private void workOrderCancelBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workOrderCancelBtActionPerformed
        // TODO add your handling code here:
        this.closeWindow();
    }//GEN-LAST:event_workOrderCancelBtActionPerformed

    private void employeeComboBoxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_employeeComboBoxPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        EmployeeComboBoxModel employeeComboBoxModel = (EmployeeComboBoxModel) employeeComboBox.getModel();
        this.employeeService.setInstance(employeeComboBoxModel.getSelectedItem());
        
    }//GEN-LAST:event_employeeComboBoxPopupMenuWillBecomeInvisible

    private void workOrderAdvanceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workOrderAdvanceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workOrderAdvanceTxtActionPerformed

    private void workOrderAdvanceTxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_workOrderAdvanceTxtPropertyChange
        // TODO add your handling code here:
        //balanceTotalCalculate();
    }//GEN-LAST:event_workOrderAdvanceTxtPropertyChange

    private void workOrderAdvanceTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_workOrderAdvanceTxtKeyReleased
        // TODO add your handling code here:
        balanceTotalCalculate();
    }//GEN-LAST:event_workOrderAdvanceTxtKeyReleased

    private void balanceTotalCalculate(){
        Double temp;
        temp = Double.valueOf(this.workOrderTotalTxt.getText()) - Double.valueOf(this.workOrderAdvanceTxt.getText());
        this.workOrderBalanceTxt.setText(String.valueOf(temp));
    }
    
    //Método encargado de cerrar todos los procesos de un JDialog
    private void closeWindow() {
        this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox employeeComboBox;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox pruebaJC;
    private javax.swing.JComboBox searchNameComboText;
    private javax.swing.JButton workOrderAddBt;
    private javax.swing.JTextField workOrderAdvanceTxt;
    private javax.swing.JTextField workOrderBalanceTxt;
    private javax.swing.JButton workOrderCancelBt;
    private com.toedter.calendar.JDateChooser workOrderDeliveryDc;
    private javax.swing.JTable workOrderDetailTable;
    private javax.swing.JRadioButton workOrderHightPriorityJrb;
    private com.toedter.calendar.JDateChooser workOrderIssueDc;
    private javax.swing.JRadioButton workOrderLowPriorityJrb;
    private javax.swing.JRadioButton workOrderNormalPriorityJrb;
    private javax.swing.JTextField workOrderNumberTxt;
    private javax.swing.JTextField workOrderPersonAddressTxt;
    private javax.swing.JTextField workOrderPersonIdentificationTxt;
    private javax.swing.JTextField workOrderPersonLastNameTxt;
    private javax.swing.JTextField workOrderPersonNameTxt;
    private javax.swing.JTextField workOrderPersonPhoneTxt;
    private javax.swing.JButton workOrderSaveBt;
    private javax.swing.JComboBox<String> workOrderStateCb;
    private javax.swing.JTextField workOrderTotalTxt;
    // End of variables declaration//GEN-END:variables

}
